simuloto:
    resource: "@SimulotoBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

coresphere_console:
    resource: .
    type: extra