<?php

namespace SimulotoBundle\Repository;

/**
 * EuromillionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EuromillionsRepository extends \Doctrine\ORM\EntityRepository
{
}
