<?php

namespace SimulotoBundle\Repository;

/**
 * LotoFrSimulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotoFrSimulationRepository extends \Doctrine\ORM\EntityRepository
{
}
