<?php

namespace SimulotoBundle\Repository;

/**
 * LottoSimulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LottoSimulationRepository extends \Doctrine\ORM\EntityRepository
{
}
