<?php

namespace SimulotoBundle\Repository;

/**
 * SimulotteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimulotteryRepository extends \Doctrine\ORM\EntityRepository
{
}
